version: 2.1

jobs:

  Update-S3-Bucket:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 

      - run:
          name: Install Packages (tar)
          command: |
            yum install -y tar gzip
      - run:
          name: Deploy frontend objects
          command: |
            ls -a
            mkdir destination
            cp -R $(cat mv_list) ./destination
            ls -a ./destination 
            aws s3 cp ./destination s3://devlook.tech --recursive

workflows:
  welcome:
    jobs:
      - Update-S3-Bucket:     
          filters:
            branches:
              only: [main]